# Generated by Django 4.2.15 on 2024-08-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('conteudo', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='fotos/')),
            ],
        ),
    ]
