# Generated by Django 4.2.15 on 2024-09-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='conteudo',
            field=models.TextField(max_length=255),
        ),
    ]
