# Generated by Django 4.2.15 on 2024-09-01 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_conteudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='foto',
        ),
    ]
