# Generated by Django 4.2.15 on 2024-09-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
