# Generated by Django 4.2.15 on 2024-09-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='conteudo',
            field=models.TextField(),
        ),
    ]
